# Title shown in Application Information tab.
title: Avaloq Cloud Framework
# Sub Title shown in Application Information tab.
description: The Avaloq Cloud Framework helps to deploy banking solutions on Oracle Cloud Infrastructure (OCI)
informationalText: This framework helps developers to provision a hosting environment for the Avaloq Banking Suite on Oracle Cloud Infrastructure (OCI).
schemaVersion: 1.1.0
version: "20230801"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708
logoUrl: https://imgur.com/5VPX3M0

locale: "en"
variableGroups:
  - title: "Service Blueprint"
    variables:
      - ${class}
  - title: "Hidden"
    variables:
      - tenancy_ocid
      - compartment_ocid
      - region
      - current_user_ocid
    visible: false


variables:
  class:
    title: "Classification"
    description: "Selecting the deployment model preselects appropriate resource parameter"
    type: enum
    default: "Custom Sandbox"
    enum:
      - Custom Sandbox
      - Developer Sandbox
      - User Acceptance
      - Production Environment
    required: true