# Title shown in Application Information tab.
title: Avaloq Cloud Framework
# Sub Title shown in Application Information tab.
description: The Avaloq Cloud Framework helps to deploy banking services in the cloud
informationalText: This framework helps operators to set up a hosting environment for banking applications on cloud infrastructure. A base set of resources is provisioned and configured.
schemaVersion: 0.0.2
version: "20230801"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708
logoUrl: https://imgur.com/TqZbJuY

locale: "en"
variableGroups:
  - title: "Service Blueprint"
    variables:
      - ${class}

variables:
  class:
    title: "Classification"
    description: "Selecting the Universal Credit Consumption (UCC) Model preselects appropriate resource types"
    type: enum
    default: "Custom Sandbox"
    enum:
      - "Custom Sandbox"
      - "Developer Sandbox"
      - "User Acceptance Test"
      - "Production"