# Title shown in Application Information tab.
title: Avaloq Cloud Framework
# Sub Title shown in Application Information tab.
description: The Avaloq Cloud Framework helps to deploy banking services in the cloud
informationalText: This framework helps operators to set up a hosting environment for banking applications on cloud infrastructure. A base set of resources is provisioned and configured.
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

locale: "en"
variableGroups:
  - title: "Node Configuration"
    variables:
      - ${class}

variables:
  class:
    title: "Classification"
    description: "Selecting the Universal Credit Consumption (UCC) Model preselects appropriate resource types"
    type: enum
    default: "FREE_TIER"
    enum:
      - FREE_TIER
      - TRIAL
      - PAYG
      - UCC