title: "Avaloq Cloud Framwork"
variableGroups:
  - title: "Account"
    variables:
      - {$class}

variables:
  class:
    title: "Classification"
    description: "Selecting the Universal Credit Consumption (UCC) Model preselects appropriate resource types"
    type: enum
    default: FREE_TIER
    enum:
      - FREE_TIER
      - TRIAL
      - PAYG
      - UCC