# Copyright (c) 2023 Avaloq and/or its affiliates.
# Licensed under the Apache 2.0 license shown at https://www.apache.org/licenses/LICENSE-2.0.


title: "Avaloq Cloud Framwork"
description: "The Avaloq Cloud Framework helps to deploy banking services in the cloud"
informationalText: "This framework helps operators to set up a hosting environment for banking applications on cloud infrastructure. A base set of resources is provisioned and configured."
schemaVersion: 0.0.2
version: "20230801"
locale: "en"

variableGroups:
- title: "Settings"
  visible: true
  variables:
  - tenancy_ocid
  - class

- title: "Hidden"
  visible: false
  variables:
  - current_user_ocid
  - compartment_ocid
  - current_user_ocid
  - region

variables:
# Oracle Cloud Settings
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier for your tenancy"
    visible: false
    type: string
    required: true

  class:
    title: "Classification"
    description: "Selecting the Universal Credit Consumption (UCC) Model preselects appropriate resource types"
    type: enum
    default: "FREE_TIER"
    required: true
    enum:
      - FREE_TIER
      - TRIAL
      - PAYG
      - UCC